name :
	 Qcachegrind
homepage :
	 https://kcachegrind.github.io/
url :
	 https://download.kde.org/stable/applications/18.04.3/src/kcachegrind-18.04.3.tar.xz
description :
	 Visualize data generated by Cachegrind and Calltree
build_deps :
link_deps :
	 graphviz
	 qt
optional_deps :
conflicts :
resource :
	 []
	 []
patches :
EOF_patch :
install :
	 cd "qcachegrind" do
	 system "#{Formula["qt"].opt_bin}/qmake", "-spec", "macx-clang",
	 "-config", "release"
	 system "make"
	 prefix.install "qcachegrind.app"
	 bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
	 end
